noteapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('notes.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notes/urls.py
from django.urls import path
from .views import *
from . import views

urlpatterns=[
    path('noteadd', NoteAdd, name='noteadd'),
    path('', ViewNote, name='noteshow'),
    path('edit/<int:id>', EditNote),
    path('update/<int:id>', UpdateNote),
    path('delete/<int:id>', DestroyNote),
]

notes/models.py
from django.db import models

# Create your models here.
class Note(models.Model):
    title=models.TextField()
    body=models.TextField()
    def __str__(self):
        return self.title

notes/forms.py
from .models import *
from django import forms

class NoteForm(forms.ModelForm):
    class Meta:
        model=Note
        fields=['title','body']

notes/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from .models import Note
from .forms import NoteForm
# Create your views here.
def NoteAdd(request):
    if request.method == "POST":
        form = NoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = NoteForm()
    return render(request, "notes/noteadd.html", {"form": form})


def ViewNote(request):
    notes = Note.objects.all()
    return render(request, "notes/index.html", {"notes":notes})


def EditNote(request, id):
    note = Note.objects.get(id=id)
    return render(request, "notes/noteedit.html", {"note":note})


def UpdateNote(request, id):
    note = Note.objects.get(id=id)
    form = NoteForm(request.POST, instance=note)
    if form.is_valid():
        form.save()
        return redirect("/")
    return render(request, "notes/noteedit.html", {"note":note})


def DestroyNote(request, id):
    note = Note.objects.get(id=id)
    note.delete()
    return redirect("/")

notes/templates/notes/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>

<body>
                <div class="row">
                {% for note in notes %}
                <div class="col-lg-5 card border-dark mb-3 mr-1" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{note.title}}</h5>
                        <p class="card-text">{{note.body}}</p>
                        <a href="/edit/{{ note.id }}"><button type="button" class="btn btn-outline-primary btn-sm">Edit</button></a>
                        <a href="/delete/{{ note.id }}"><button type="button" class="btn btn-outline-primary btn-sm">Delete</button></a>
                    </div>
                </div>
                {% endfor %}
                </div>
                <br>
                <br>
                <center><a href="{% url 'noteadd' %}" class="btn btn-primary">Add New Note</a></center>
</body>

</html>

notes/templates/notes/noteadd.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>

<body>
    <form method="POST" class="post-form" action="">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Enter Details</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Title:</label>
                <div class="col-sm-4">
                    {{ form.title }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Body:</label>
                <div class="col-sm-4">
                    {{ form.body }}
                </div>
            </div>
            <div class="form-group row">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
</body>

</html>

notes/templates/notes/noteedit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>

<body>
    <form method="POST" class="post-form" action="/update/{{note.id}}">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm 4">
                    <h3>Update Details</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Title:</label>
                <div class="col-sm 4">
                    <input type="text" name="title" id="id_title" value="{{ note.title }}">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label">Body:</label>
                <div class="col-sm 4">
                    <input type="text" name="body" id="id_body" value="{{ note.body }}">
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm 4">
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </div>
        </div>
    </form>
</body>

</html>

notes/templates/notes/noteshow.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>

<body>
                <div class="row">
                {% for note in notes %}
                <div class="col-lg-5 card border-dark mb-3 mr-1" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{note.title}}</h5>
                        <p class="card-text">{{note.body}}</p>
                        <a href="/edit/{{ note.id }}"><button type="button" class="btn btn-outline-primary btn-sm">Edit</button></a>
                        <a href="/delete/{{ note.id }}"><button type="button" class="btn btn-outline-primary btn-sm">Delete</button></a>
                    </div>
                </div>
                {% endfor %}
                </div>
                <br>
                <br>
                <center><a href="{% url 'noteadd' %}" class="btn btn-primary">Add New Note</a></center>
</body>

</html>